export const languages = [
    { name: "English", value: "en-US" },
    { name: "Hindi", value: "hi-IN" },
    { name: "Urdu", value: "ur-PK" },
    { name: "Arabic", value: "ar-SA" },
    { name: "Bengali", value: "bn-IN" },
    { name: "Chinese (Mandarin)", value: "cmn-CN" },
    { name: "French", value: "fr-FR" },
    { name: "German", value: "de-DE" },
    { name: "Indonesian", value: "id-ID" },
    { name: "Italian", value: "it-IT" },
    { name: "Japanese", value: "ja-JP" },
    { name: "Korean", value: "ko-KR" },
    { name: "Portuguese", value: "pt-BR" },
    { name: "Russian", value: "ru-RU" },
    { name: "Spanish", value: "es-US" },
    { name: "Turkish", value: "tr-TR" },
    { name: "Vietnamese", value: "vi-VN" },
    { name: "Dutch", value: "nl-NL" },
    { name: "Polish", value: "pl-PL" },
    { name: "Swedish", value: "sv-SE" },
    { name: "Thai", value: "th-TH" },
];
