
import { type Metadata } from 'next';
import { ProductDescriptionGeneratorClient } from '@/components/product-description-generator-client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { CheckCircle } from 'lucide-react';
import Link from 'next/link';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';


export const metadata: Metadata = {
  title: 'Free AI Product Description Generator | SEO-Optimized Copy',
  description: 'Generate compelling, high-converting product descriptions for your e-commerce store. Our AI tool creates SEO-friendly copy for any product.',
};

const benefits = [
    "Increase conversions with persuasive copy.",
    "Improve SEO with keyword-rich descriptions.",
    "Save hours of writing time.",
    "Create a consistent brand voice across all products."
];

const faqs = [
    {
        question: "What is an AI product description generator?",
        answer: "An AI product description generator is a tool that uses artificial intelligence to write compelling and persuasive descriptions for e-commerce products. You provide details like the product name, features, and target audience, and the AI crafts a description designed to attract customers and improve sales."
    },
    {
        question: "How can this tool improve my product's SEO?",
        answer: "Our product description AI is designed to be SEO-optimized. It naturally incorporates relevant keywords based on your product name and category, helping your product pages rank higher in search engine results on Google, Amazon, and other platforms."
    },
    {
        question: "Is this product description generator free?",
        answer: "Yes, our AI product description generator is completely free to use. It's a powerful tool for e-commerce store owners who want to create high-quality content without the cost of hiring a professional copywriter."
    },
    {
        question: "Can I use this for my Shopify or Amazon store?",
        answer: "Absolutely. The descriptions generated by our tool are perfect for any e-commerce platform, including Shopify, Amazon, Etsy, and WooCommerce. The copy is structured to be readable and persuasive, which works well across all major online marketplaces."
    },
    {
        question: "How do I get the best product description from the AI?",
        answer: "For the best results, provide as much detail as possible. List the key features and benefits clearly, define your target audience accurately, and choose a tone that matches your brand. The more information the AI has, the more tailored and effective the generated description will be."
    }
];

const schema = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "SoftwareApplication",
      "name": "AI Product Description Generator",
      "applicationCategory": "BusinessApplication",
      "operatingSystem": "Web",
      "description": "A free AI tool to generate compelling, high-converting, and SEO-friendly product descriptions for e-commerce stores.",
      "url": "https://aitoolkitpro.netlify.app/tools/product-description-generator",
      "offers": {
        "@type": "Offer",
        "price": "0",
        "priceCurrency": "USD"
      },
      "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "4.8",
        "reviewCount": "175"
      },
      "author": {
        "@type": "Organization",
        "name": "AI Toolkit Pro"
      }
    },
    {
      "@type": "FAQPage",
      "mainEntity": faqs.map(faq => ({
        "@type": "Question",
        "name": faq.question,
        "acceptedAnswer": {
          "@type": "Answer",
          "text": faq.answer
        }
      }))
    }
  ]
};

export default function ProductDescriptionGeneratorPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <div className="container py-12 md:py-20">
        <div className="grid lg:grid-cols-5 gap-12">
          <div className="lg:col-span-3">
              <h1 className="font-headline text-4xl md:text-5xl font-bold gradient-text">
                  AI Product Description Generator
              </h1>
              <div className="mt-4 p-6 rounded-lg bg-muted/50 border">
                <p className="text-lg text-muted-foreground">
                  Turn product features into compelling descriptions that sell with our <strong>AI product description generator</strong>. Let our <strong>product description AI</strong> craft the perfect, SEO-friendly copy for your e-commerce store and boost your conversions. This <strong>free product description generator</strong> is designed to save you time and effort while producing high-quality content. As the <strong>best product description generator</strong>, it helps you create engaging and persuasive descriptions that resonate with your target audience.
                </p>
              </div>

              <div className="mt-8">
                  <ProductDescriptionGeneratorClient />
              </div>
          </div>
          <div className="lg:col-span-2 space-y-8">
              <Card>
                  <CardHeader>
                      <CardTitle className="font-headline text-2xl">How to Use</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                      <p><strong>1. Enter Details:</strong> Provide the product name, category, features, and target audience.</p>
                      <p><strong>2. Select Tone:</strong> Choose a tone that matches your brand (e.g., Professional, SEO-optimized).</p>
                      <p><strong>3. Generate:</strong> Click the "Generate Description" button to let the AI create the copy.</p>
                      <p><strong>4. Copy & Use:</strong> Copy the generated description and paste it directly into your e-commerce platform.</p>
                  </CardContent>
              </Card>

               <Card>
                  <CardHeader>
                      <CardTitle className="font-headline text-2xl">Benefits</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-3">
                      {benefits.map((benefit, index) => (
                          <div key={index} className="flex items-start">
                              <CheckCircle className="h-5 w-5 text-green-500 mr-3 mt-1 flex-shrink-0" />
                              <span>{benefit}</span>
                          </div>
                      ))}
                  </CardContent>
              </Card>
          </div>
        </div>
      </div>
      <section className="py-16">
        <div className="container max-w-4xl">
            <div className="prose dark:prose-invert mx-auto">
                <h2>Boost Your Sales with an AI Product Description Generator</h2>
                <p>In the competitive world of e-commerce, a compelling product description can make all the difference. An <strong>AI product description generator</strong> is a powerful tool that can help you create persuasive and SEO-friendly copy that drives sales. Our platform offers a state-of-the-art <strong>product description AI</strong> that can transform your product features into engaging narratives. It's the perfect solution for online store owners who want to create high-quality content without the hassle of writing it themselves. For more e-commerce tips, check out <a href="https://www.bigcommerce.com/blog/" target="_blank" rel="noopener noreferrer">BigCommerce's blog</a>.</p>
                
                <p>Our tool is designed to be the <strong>best product description generator</strong> by providing a combination of creativity and optimization. The <strong>free product description generator</strong> is easy to use; simply enter your product details, and the AI will do the rest. This makes it an invaluable <strong>ecommerce product description generator</strong> for businesses of all sizes. The <strong>AI generated product descriptions</strong> are not only well-written but also optimized for search engines, helping you attract more organic traffic to your store. You can also generate great ad copy with our <Link href="/tools/ad-copy-generator">Ad Copy Generator</Link>.</p>
                
                <h3>Create High-Converting Copy in Minutes</h3>
                <p>The <strong>product description writer</strong> AI can create descriptions for a wide range of products, from electronics to fashion. It's a versatile <strong>Shopify product description generator</strong> that can be used with any e-commerce platform. The <strong>AI product description writer</strong> is also a great tool for creating content for Amazon, eBay, and other marketplaces. Our <strong>free AI product description generator</strong> is a must-have for any serious online seller. You can also generate a <Link href="/tools/slogan-generator">slogan</Link> for your product.</p>
                
                <p>Whether you need a short and catchy description or a detailed and informative one, our <strong>product description generator from keywords</strong> can help you achieve your goals. It's a powerful <strong>product description maker</strong> that can save you time and money on content creation. Stop struggling with writer's block and start using the power of AI to create compelling product descriptions that sell. Try our <strong>best free product description generator</strong> today and see the difference it can make for your business.</p>
            </div>
        </div>
      </section>
      <section className="py-16 md:py-24">
        <div className="container max-w-3xl">
          <h2 className="font-headline text-3xl font-bold text-center mb-8">
            Frequently Asked Questions
          </h2>
          <Accordion type="single" collapsible className="w-full space-y-4">
            {faqs.map((faq, index) => (
                <AccordionItem 
                    value={`item-${index}`} 
                    key={index}
                    className="bg-card/50 backdrop-blur-sm border border-border/50 rounded-xl px-6 animate-pop-in"
                    style={{ animationDelay: `${index * 0.1}s`}}
                >
                    <AccordionTrigger className="font-headline text-lg text-left hover:no-underline">{faq.question}</AccordionTrigger>
                    <AccordionContent className="text-base text-muted-foreground">
                        {faq.answer}
                    </AccordionContent>
                </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>
    </>
  );
}
