
import { type Metadata } from 'next';
import { Card, CardContent } from '@/components/ui/card';

export const metadata: Metadata = {
  title: 'Copyright Disclaimer | AI Toolkit Pro',
  description: 'Official copyright disclaimer for AI Toolkit Pro. Learn about content ownership, fair use, and responsibilities regarding AI-generated materials.',
};

const schema = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  "name": "Copyright Disclaimer",
  "url": "https://www.aitoolkitpro.com/copyright-disclaimer",
  "description": "Official copyright disclaimer for AI Toolkit Pro. Learn about content ownership, fair use, and responsibilities regarding AI-generated materials.",
  "publisher": {
    "@type": "Organization",
    "name": "AI Toolkit Pro",
    "logo": {
      "@type": "ImageObject",
      "url": "https://www.aitoolkitpro.com/logo.png"
    }
  }
};

export default function CopyrightDisclaimerPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <div className="container max-w-3xl p-4 sm:p-6 md:p-8">
        <div className="text-center mb-10">
          <h1 className="font-headline text-3xl md:text-4xl font-bold">Copyright Disclaimer</h1>
          <p className="mt-2 text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
        </div>

        <Card className="bg-card/50">
            <CardContent className="p-6 space-y-6 text-sm md:text-base text-muted-foreground">
                <p>
                  The content, organization, graphics, design, compilation, and other matters related to the AI Toolkit Pro website are protected under applicable copyrights and other proprietary laws, including but not limited to intellectual property laws. The copying, reproduction, use, modification, or publication by you of any such matters or any part of the Site is strictly prohibited without our express prior written permission.
                </p>

                <div className="space-y-2">
                  <h2 className="text-lg font-semibold text-foreground">1. Ownership of Content</h2>
                  <p>
                    All content on this website, including text, graphics, logos, icons, images, audio clips, and software, is the property of AI Toolkit Pro or its content suppliers and is protected by international copyright laws.
                  </p>
                </div>

                <div className="space-y-2">
                  <h2 className="text-lg font-semibold text-foreground">2. AI-Generated Content</h2>
                  <p>
                    The content generated by the AI tools on this website (e.g., images, text, scripts, logos) is created by third-party artificial intelligence models. While you are generally free to use this content for personal and commercial purposes, you are solely responsible for ensuring that your use of the generated content complies with all applicable laws and the terms of service of the respective AI providers. AI Toolkit Pro does not claim any ownership rights over the content you generate using our tools.
                  </p>
                </div>

                <div className="space-y-2">
                  <h2 className="text-lg font-semibold text-foreground">3. Fair Use Disclaimer</h2>
                  <p>
                    This website may contain copyrighted material, the use of which has not always been specifically authorized by the copyright owner. We are making such material available in our efforts to advance understanding of technological, creative, and social issues. We believe this constitutes a "fair use" of any such copyrighted material as provided for in section 107 of the US Copyright Law.
                  </p>
                </div>

                <div className="space-y-2">
                  <h2 className="text-lg font-semibold text-foreground">4. No Guarantees</h2>
                  <p>
                    While we strive to provide accurate and high-quality tools, AI Toolkit Pro makes no guarantees regarding the accuracy, completeness, or reliability of any content generated by the AI. The content is provided on an "as is" basis without warranties of any kind.
                  </p>
                </div>
                
                <div className="space-y-2">
                  <h2 className="text-lg font-semibold text-foreground">5. Contact Us</h2>
                  <p>
                    If you have any questions about this Copyright Disclaimer, please contact us through our contact page.
                  </p>
                </div>
            </CardContent>
        </Card>
      </div>
    </>
  );
}
