import { type Metadata } from 'next';
import { DreamInterpreterClient } from '@/components/dream-interpreter-client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { CheckCircle } from 'lucide-react';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"


export const metadata: Metadata = {
  title: 'Free AI Dream Interpreter | Understand Your Dreams in Any Language',
  description: 'Unlock the meanings behind your dreams with our free AI Dream Interpreter. Get instant analysis of symbols, emotions, and context in over 100 languages.',
};

const benefits = [
    "Gain insight into your subconscious mind.",
    "Understand the symbols and themes in your dreams.",
    "Explore psychological and spiritual perspectives.",
    "Get interpretations in your native language."
];

export default function DreamInterpreterPage() {
  return (
    <div className="container py-12 md:py-20">
      <div className="grid lg:grid-cols-5 gap-12">
        <div className="lg:col-span-3">
            <h1 className="font-headline text-4xl md:text-5xl font-bold">
                AI Dream Interpreter
            </h1>
            <p className="mt-4 text-lg text-muted-foreground">
                Describe your dream in any language, and our AI will provide a thoughtful interpretation to help you understand its meaning.
            </p>

            <div className="mt-8">
                <DreamInterpreterClient />
            </div>
        </div>
        <div className="lg:col-span-2 space-y-8">
            <Card>
                <CardHeader>
                    <CardTitle className="font-headline text-2xl">How to Use</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                    <p><strong>1. Describe Your Dream:</strong> Write down everything you can remember about your dream in the text area.</p>
                    <p><strong>2. Choose Language:</strong> Select the language you want the interpretation in.</p>
                    <p><strong>3. Generate:</strong> Click the "Interpret Dream" button to get your AI-powered analysis.</p>
                    <p><strong>4. Reflect:</strong> Read the interpretation and reflect on how it might relate to your waking life.</p>
                </CardContent>
            </Card>

             <Card>
                <CardHeader>
                    <CardTitle className="font-headline text-2xl">Benefits</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                    {benefits.map((benefit, index) => (
                        <div key={index} className="flex items-start">
                            <CheckCircle className="h-5 w-5 text-green-500 mr-3 mt-1 flex-shrink-0" />
                            <span>{benefit}</span>
                        </div>
                    ))}
                </CardContent>
            </Card>

            <Card>
                <CardHeader>
                    <CardTitle className="font-headline text-2xl">Frequently Asked Questions</CardTitle>
                </CardHeader>
                <CardContent>
                    <Accordion type="single" collapsible className="w-full">
                        <AccordionItem value="item-1">
                            <AccordionTrigger>Is this tool free?</AccordionTrigger>
                            <AccordionContent>
                            Yes, our AI Dream Interpreter is 100% free to use. There are no hidden fees or subscriptions.
                            </AccordionContent>
                        </AccordionItem>
                        <AccordionItem value="item-2">
                            <AccordionTrigger>Is the interpretation accurate?</AccordionTrigger>
                            <AccordionContent>
                            The interpretation is generated by AI and is intended for entertainment and self-reflection purposes. It is not a substitute for professional psychological advice.
                            </AccordionContent>
                        </AccordionItem>
                        <AccordionItem value="item-3">
                            <AccordionTrigger>Can I enter my dream in a language other than English?</AccordionTrigger>
                            <AccordionContent>
                            Yes, you can write your dream description in any of the supported languages. The AI will analyze it and provide the interpretation in the language you select.
                            </AccordionContent>
                        </AccordionItem>
                    </Accordion>
                </CardContent>
            </Card>
        </div>
      </div>
    </div>
  );
}
