import { type Metadata } from 'next';
import { DreamInterpreterClient } from '@/components/dream-interpreter-client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { CheckCircle } from 'lucide-react';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"


export const metadata: Metadata = {
  title: 'Free AI Dream Interpreter | Understand Your Dreams in Any Language',
  description: 'Unlock the meanings behind your dreams with our free AI Dream Interpreter. Get instant analysis of symbols, emotions, and context in over 100 languages.',
};

const benefits = [
    "Gain insight into your subconscious mind.",
    "Understand the symbols and themes in your dreams.",
    "Explore psychological and spiritual perspectives.",
    "Get interpretations in your native language."
];

const faqs = [
    {
        question: "1. Is this tool free?",
        answer: "Yes, our AI Dream Interpreter is 100% free to use. There are no hidden fees or subscriptions."
    },
    {
        question: "2. Is the interpretation accurate?",
        answer: "The interpretation is generated by AI and is intended for entertainment and self-reflection purposes. It is not a substitute for professional psychological advice."
    },
    {
        question: "3. Can I enter my dream in a language other than English?",
        answer: "Yes, you can write your dream description in any of the supported languages. The AI will analyze it and provide the interpretation in the language you select."
    },
    {
        question: "4. Is my dream description kept private?",
        answer: "Yes, absolutely. We do not store your dream descriptions or the interpretations on our servers. Your privacy is our priority."
    },
    {
        question: "5. How detailed should my dream description be?",
        answer: "The more detail you provide, the better the interpretation will be. Try to include key characters, objects, locations, colors, and any feelings or emotions you experienced in the dream."
    },
    {
        question: "6. Does the AI use a specific psychological theory?",
        answer: "The AI has been trained on a vast amount of text, including works on psychology (like Freudian and Jungian analysis), mythology, and cultural symbolism. It synthesizes these different perspectives to provide a comprehensive interpretation."
    },
    {
        question: "7. What if I have the same dream repeatedly?",
        answer: "Recurring dreams often point to an unresolved issue or a persistent thought pattern in your waking life. You can use the interpreter each time to see if new details emerge or if the interpretation offers a consistent theme to reflect upon."
    }
];

export default function DreamInterpreterPage() {
  return (
    <div className="container py-12 md:py-20">
      <div className="grid lg:grid-cols-5 gap-12">
        <div className="lg:col-span-3">
            <h1 className="font-headline text-4xl md:text-5xl font-bold">
                AI Dream Interpreter
            </h1>
            <p className="mt-4 text-lg text-muted-foreground">
                Describe your dream in any language, and our AI will provide a thoughtful interpretation to help you understand its meaning. Our free AI dream interpreter offers instant analysis of symbols, emotions, and context to unlock the secrets of your subconscious. Gain insights from psychological and spiritual perspectives, with interpretations available in over 100 languages. Start understanding your dreams today with our easy-to-use tool.
            </p>

            <div className="mt-8">
                <DreamInterpreterClient />
            </div>
        </div>
        <div className="lg:col-span-2 space-y-8">
            <Card>
                <CardHeader>
                    <CardTitle className="font-headline text-2xl">How to Use</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                    <p><strong>1. Describe Your Dream:</strong> Write down everything you can remember about your dream in the text area.</p>
                    <p><strong>2. Choose Language:</strong> Select the language you want the interpretation in.</p>
                    <p><strong>3. Generate:</strong> Click the "Interpret Dream" button to get your AI-powered analysis.</p>
                    <p><strong>4. Reflect:</strong> Read the interpretation and reflect on how it might relate to your waking life.</p>
                </CardContent>
            </Card>

             <Card>
                <CardHeader>
                    <CardTitle className="font-headline text-2xl">Benefits</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                    {benefits.map((benefit, index) => (
                        <div key={index} className="flex items-start">
                            <CheckCircle className="h-5 w-5 text-green-500 mr-3 mt-1 flex-shrink-0" />
                            <span>{benefit}</span>
                        </div>
                    ))}
                </CardContent>
            </Card>

            <Card>
                <CardHeader>
                    <CardTitle className="font-headline text-2xl">Frequently Asked Questions</CardTitle>
                </CardHeader>
                <CardContent>
                    <Accordion type="single" collapsible className="w-full space-y-4">
                        {faqs.map((faq, index) => (
                             <AccordionItem 
                                value={`item-${index + 1}`} 
                                key={index} 
                                className="bg-background/50 border rounded-lg transition-all duration-300 data-[state=open]:border-primary data-[state=open]:shadow-lg data-[state=open]:shadow-primary/10"
                            >
                                <AccordionTrigger className="text-left px-6 hover:no-underline font-semibold">
                                    {faq.question}
                                </AccordionTrigger>
                                <AccordionContent className="px-6 pb-6">
                                    {faq.answer}
                                </AccordionContent>
                            </AccordionItem>
                        ))}
                    </Accordion>
                </CardContent>
            </Card>
        </div>
      </div>
    </div>
  );
}
