
import { type Metadata } from 'next';
import { AiMusicGeneratorClient } from '@/components/ai-music-generator-client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { CheckCircle } from 'lucide-react';
import Link from 'next/link';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';


export const metadata: Metadata = {
  title: 'Free AI Music Generator | Create Music with Lyria',
  description: 'Generate original, high-quality music in real-time from text prompts using Google\'s Lyria AI model. Create instrumentals, soundscapes, and full tracks for free.',
};

const benefits = [
    "Create original, royalty-free music in seconds.",
    "No musical knowledge or instruments required.",
    "Generate full tracks, instrumentals, or sound effects.",
    "Perfect for content creators, filmmakers, and developers."
];

const faqs = [
    {
        question: "What is an AI music generator?",
        answer: "An AI music generator is a tool that uses artificial intelligence to compose and produce original music. Our tool uses Google's advanced Lyria model to create music from simple text descriptions, allowing anyone to become a composer."
    },
    {
        question: "What is Lyria?",
        answer: "Lyria is a cutting-edge music generation model developed by Google's DeepMind. It's known for producing high-quality instrumentals and sound, offering a new level of creativity and control in AI music generation."
    },
    {
        question: "Is the music generated by the AI royalty-free?",
        answer: "Yes, the music you create is generally royalty-free for your projects, such as YouTube videos, podcasts, games, or social media content. This makes it an invaluable resource for creators who need custom soundtracks."
    },
    {
        question: "Can I generate music in a specific genre or mood?",
        answer: "Absolutely. The power of Lyria lies in its ability to understand descriptive prompts. You can specify the genre (e.g., 'cinematic orchestral,' 'upbeat synth-pop,' 'lo-fi hip-hop'), mood (e.g., 'somber and reflective,' 'adventurous and epic'), instruments, and tempo to guide the AI."
    },
    {
        question: "Do I need any music theory knowledge to use this tool?",
        answer: "Not at all. This tool is designed for everyone, regardless of musical background. If you can describe the music you imagine, you can create it. It's a fantastic way to produce custom soundtracks without needing to know music theory or how to play an instrument."
    }
];

const schema = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "SoftwareApplication",
      "name": "AI Music Generator (Lyria)",
      "applicationCategory": "MultimediaApplication",
      "operatingSystem": "Web",
      "description": "A free AI tool to generate original music from text prompts using Google's Lyria model.",
      "url": "https://ai-toolkit-pro.vercel.app/tools/ai-music-generator",
      "offers": {
        "@type": "Offer",
        "price": "0",
        "priceCurrency": "USD"
      },
      "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "4.9",
        "reviewCount": "215"
      },
      "author": {
        "@type": "Organization",
        "name": "AI Toolkit Pro"
      }
    },
    {
      "@type": "FAQPage",
      "mainEntity": faqs.map(faq => ({
        "@type": "Question",
        "name": faq.question,
        "acceptedAnswer": {
          "@type": "Answer",
          "text": faq.answer
        }
      }))
    }
  ]
};

export default function AiMusicGeneratorPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <div className="container py-12 md:py-20">
        <div className="grid lg:grid-cols-5 gap-12">
          <div className="lg:col-span-3">
              <h1 className="font-headline text-4xl md:text-5xl font-bold gradient-text">
                  AI Music Generator (Lyria)
              </h1>
              <div className="mt-4 p-6 rounded-lg bg-muted/50 border">
                <p className="text-lg text-muted-foreground">
                  Transform your ideas into original music with our <strong>AI music generator</strong>, powered by Google's advanced Lyria model. Describe the genre, mood, or instruments, and our <strong>text to music AI</strong> will compose a unique track for you in real-time. This <strong>free AI music generator</strong> is perfect for creating royalty-free background music for videos, podcasts, and games.
                </p>
              </div>

              <div className="mt-8">
                  <AiMusicGeneratorClient />
              </div>
          </div>
          <div className="lg:col-span-2 space-y-8">
              <Card>
                  <CardHeader>
                      <CardTitle className="font-headline text-2xl">How to Use</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                      <p><strong>1. Describe Your Music:</strong> Write a detailed prompt describing the music you want (e.g., "A chill lo-fi hip-hop track for studying").</p>
                      <p><strong>2. Set Duration:</strong> Choose how long you want the music clip to be.</p>
                      <p><strong>3. Generate:</strong> Click the "Generate Music" button and listen as the AI composes your track.</p>
                      <p><strong>4. Download:</strong> Once generated, you can download the audio file to use in your projects.</p>
                  </CardContent>
              </Card>

               <Card>
                  <CardHeader>
                      <CardTitle className="font-headline text-2xl">Benefits</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-3">
                      {benefits.map((benefit, index) => (
                          <div key={index} className="flex items-start">
                              <CheckCircle className="h-5 w-5 text-green-500 mr-3 mt-1 flex-shrink-0" />
                              <span>{benefit}</span>
                          </div>
                      ))}
                  </CardContent>
              </Card>
          </div>
        </div>
      </div>
      <section className="py-16">
        <div className="container max-w-4xl">
            <div className="prose dark:prose-invert mx-auto">
                <h2>Unleash Your Inner Composer with an AI Music Generator</h2>
                <p>Music creation has never been more accessible. An <strong>AI music generator</strong> is a revolutionary tool that allows anyone to become a composer, regardless of their musical background. Our platform leverages Google's powerful Lyria model to provide a <strong>free AI music generator</strong> that transforms your text descriptions into high-quality, original music. Whether you're a content creator needing a custom soundtrack or a developer looking for game audio, this tool is for you. Learn about the technology at <a href="https://deepmind.google/discover/blog/transforming-the-future-of-music-creation/" target="_blank" rel="noopener noreferrer">Google DeepMind's Blog</a>.</p>
                
                <p>The <strong>AI generated music</strong> is not just a random assortment of notes; it's a cohesive piece of music that follows the genre, mood, and instrumentation you specify. This <strong>text to music generator free</strong> service is perfect for creating everything from epic orchestral scores to chill electronic beats. The <strong>music generator AI</strong> is a powerful creative partner that can help you bring your artistic vision to life. For lyrics to go with your music, try our <Link href="/tools/poem-lyrics-generator">Poem & Lyrics Generator</Link>.</p>
            </div>
        </div>
      </section>
      <section className="py-16 md:py-24">
        <div className="container max-w-3xl">
          <h2 className="font-headline text-3xl font-bold text-center mb-8">
            Frequently Asked Questions
          </h2>
          <Accordion type="single" collapsible className="w-full space-y-4">
            {faqs.map((faq, index) => (
                <AccordionItem 
                    value={`item-${index}`} 
                    key={index}
                    className="bg-card/50 backdrop-blur-sm border border-border/50 rounded-xl px-6 animate-pop-in"
                    style={{ animationDelay: `${index * 0.1}s`}}
                >
                    <AccordionTrigger className="font-headline text-lg text-left hover:no-underline">{faq.question}</AccordionTrigger>
                    <AccordionContent className="text-base text-muted-foreground">
                        {faq.answer}
                    </AccordionContent>
                </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>
    </>
  );
}
