
import { type Metadata } from 'next';
import { HoroscopeGeneratorClient } from '@/components/horoscope-generator-client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { CheckCircle } from 'lucide-react';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"


export const metadata: Metadata = {
  title: 'Free AI Horoscope Generator | Daily, Weekly, Monthly',
  description: 'Get your free, personalized horoscope for any zodiac sign. Our AI generates daily, weekly, and monthly predictions for love, career, and health.',
};

const benefits = [
    "Get personalized daily, weekly, and monthly insights.",
    "Plan your future with predictions for love, career, and health.",
    "Discover your lucky numbers and colors.",
    "Available in multiple languages for a global audience."
];

const faqs = [
    {
        question: "1. Is this tool free to use?",
        answer: "Yes, our AI Horoscope Generator is 100% free. There are no hidden fees or subscriptions."
    },
    {
        question: "2. How accurate are the predictions?",
        answer: "The horoscopes are generated by an AI for entertainment purposes. While they are designed to be insightful and positive, they should not be taken as professional astrological or financial advice."
    },
    {
        question: "3. Can I get a horoscope for my friend?",
        answer: "Absolutely! You can select any zodiac sign and generate a horoscope for friends and family."
    },
    {
        question: "4. What information does the horoscope include?",
        answer: "Each horoscope provides detailed predictions for three key life areas: Love & Relationships, Career & Finance, and Health & Wellness. It also includes a lucky number and a lucky color for the selected timeframe."
    },
    {
        question: "5. Can I get horoscopes in different languages?",
        answer: "Yes, our tool supports over 20 languages. Simply select your preferred language from the dropdown menu to receive your horoscope in that language."
    },
    {
        question: "6. How does the AI generate the horoscopes?",
        answer: "The AI has been trained on a vast amount of astrological texts, patterns, and symbolic meanings. It synthesizes this knowledge to generate unique and coherent predictions based on the zodiac sign and timeframe you select."
    },
    {
        question: "7. Can I save or share my horoscope?",
        answer: "Yes. Once your horoscope is generated, you can use the 'Copy' button to copy the text to your clipboard or the 'Download' button to save it as a text file on your device."
    }
];

export default function HoroscopeGeneratorPage() {
  return (
    <div className="container py-12 md:py-20">
      <div className="grid lg:grid-cols-5 gap-12">
        <div className="lg:col-span-3">
            <h1 className="font-headline text-4xl md:text-5xl font-bold">
                AI Horoscope Generator
            </h1>
            <div className="mt-4 p-6 rounded-lg bg-muted/50 border">
              <p className="text-lg text-muted-foreground">
                Select your zodiac sign and timeframe to receive a personalized horoscope covering love, career, health, your lucky numbers, and more insightful predictions.
              </p>
            </div>

            <div className="mt-8">
                <HoroscopeGeneratorClient />
            </div>
        </div>
        <div className="lg:col-span-2 space-y-8">
            <Card>
                <CardHeader>
                    <CardTitle className="font-headline text-2xl">How to Use</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                    <p><strong>1. Select Your Sign:</strong> Choose your zodiac sign from the list.</p>
                    <p><strong>2. Choose Timeframe:</strong> Select whether you want a daily, weekly, or monthly horoscope.</p>
                    <p><strong>3. Select Language:</strong> Pick your preferred language.</p>
                    <p><strong>4. Generate:</strong> Click the "Generate Horoscope" button to get your personalized reading.</p>
                </CardContent>
            </Card>

             <Card>
                <CardHeader>
                    <CardTitle className="font-headline text-2xl">Benefits</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                    {benefits.map((benefit, index) => (
                        <div key={index} className="flex items-start">
                            <CheckCircle className="h-5 w-5 text-green-500 mr-3 mt-1 flex-shrink-0" />
                            <span>{benefit}</span>
                        </div>
                    ))}
                </CardContent>
            </Card>

            <Card>
                <CardHeader>
                    <CardTitle className="font-headline text-2xl">Frequently Asked Questions</CardTitle>
                </CardHeader>
                <CardContent>
                    <Accordion type="single" collapsible className="w-full space-y-4">
                        {faqs.map((faq, index) => (
                             <AccordionItem 
                                value={`item-${index + 1}`} 
                                key={index} 
                                className="bg-background/50 border rounded-lg transition-all duration-300 data-[state=open]:border-primary data-[state=open]:shadow-lg data-[state=open]:shadow-primary/10"
                            >
                                <AccordionTrigger className="text-left px-6 hover:no-underline font-semibold">
                                    {faq.question}
                                </AccordionTrigger>
                                <AccordionContent className="px-6 pb-6">
                                    {faq.answer}
                                </AccordionContent>
                            </AccordionItem>
                        ))}
                    </Accordion>
                </CardContent>
            </Card>
        </div>
      </div>
    </div>
  );
}
