import { type Metadata } from 'next';
import { HoroscopeGeneratorClient } from '@/components/horoscope-generator-client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { CheckCircle } from 'lucide-react';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"


export const metadata: Metadata = {
  title: 'Free AI Horoscope Generator | Daily, Weekly, Monthly',
  description: 'Get your free, personalized horoscope for any zodiac sign. Our AI generates daily, weekly, and monthly predictions for love, career, and health.',
};

const benefits = [
    "Get personalized daily, weekly, and monthly insights.",
    "Plan your future with predictions for love, career, and health.",
    "Discover your lucky numbers and colors.",
    "Available in multiple languages for a global audience."
];

export default function HoroscopeGeneratorPage() {
  return (
    <div className="container py-12 md:py-20">
      <div className="grid lg:grid-cols-5 gap-12">
        <div className="lg:col-span-3">
            <h1 className="font-headline text-4xl md:text-5xl font-bold">
                AI Horoscope Generator
            </h1>
            <p className="mt-4 text-lg text-muted-foreground">
                Select your zodiac sign and timeframe to receive a personalized horoscope covering love, career, health, and more.
            </p>

            <div className="mt-8">
                <HoroscopeGeneratorClient />
            </div>
        </div>
        <div className="lg:col-span-2 space-y-8">
            <Card>
                <CardHeader>
                    <CardTitle className="font-headline text-2xl">How to Use</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                    <p><strong>1. Select Your Sign:</strong> Choose your zodiac sign from the list.</p>
                    <p><strong>2. Choose Timeframe:</strong> Select whether you want a daily, weekly, or monthly horoscope.</p>
                    <p><strong>3. Select Language:</strong> Pick your preferred language.</p>
                    <p><strong>4. Generate:</strong> Click the "Generate Horoscope" button to get your personalized reading.</p>
                </CardContent>
            </Card>

             <Card>
                <CardHeader>
                    <CardTitle className="font-headline text-2xl">Benefits</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                    {benefits.map((benefit, index) => (
                        <div key={index} className="flex items-start">
                            <CheckCircle className="h-5 w-5 text-green-500 mr-3 mt-1 flex-shrink-0" />
                            <span>{benefit}</span>
                        </div>
                    ))}
                </CardContent>
            </Card>

            <Card>
                <CardHeader>
                    <CardTitle className="font-headline text-2xl">Frequently Asked Questions</CardTitle>
                </CardHeader>
                <CardContent>
                    <Accordion type="single" collapsible className="w-full">
                        <AccordionItem value="item-1">
                            <AccordionTrigger>Is this tool free to use?</AccordionTrigger>
                            <AccordionContent>
                            Yes, our AI Horoscope Generator is 100% free. There are no hidden fees or subscriptions.
                            </AccordionContent>
                        </AccordionItem>
                        <AccordionItem value="item-2">
                            <AccordionTrigger>How accurate are the predictions?</AccordionTrigger>
                            <AccordionContent>
                            The horoscopes are generated by an AI for entertainment purposes. While they are designed to be insightful and positive, they should not be taken as professional advice.
                            </AccordionContent>
                        </AccordionItem>
                         <AccordionItem value="item-3">
                            <AccordionTrigger>Can I get a horoscope for my friend?</AccordionTrigger>
                            <AccordionContent>
                            Absolutely! You can select any zodiac sign and generate a horoscope for friends and family.
                            </AccordionContent>
                        </AccordionItem>
                    </Accordion>
                </CardContent>
            </Card>
        </div>
      </div>
    </div>
  );
}
