
'use client';

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { ArrowRight } from "lucide-react";
import Link from "next/link";
import { useRef, useState } from "react";
import { allTools } from "@/lib/tools";
import { Carousel, CarouselContent, CarouselItem } from "@/components/ui/carousel";
import Autoplay from "embla-carousel-autoplay";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import Image from "next/image";
import { cn } from "@/lib/utils";

const testimonials = [
    {
        name: "Alex Rivera",
        title: "Content Creator",
        quote: "The AI Script Writer is a game-changer! I went from spending hours on a video script to drafting one in minutes. My productivity has skyrocketed.",
        avatar: "https://i.pravatar.cc/150?u=alex",
        rating: 5,
    },
    {
        name: "Samantha Lee",
        title: "Small Business Owner",
        quote: "I created a professional logo for my new business in under 60 seconds using the AI Logo Maker. It's free, fast, and the results are stunning. Highly recommend!",
        avatar: "https://i.pravatar.cc/150?u=samantha",
        rating: 5,
    },
    {
        name: "Mike Chen",
        title: "Digital Marketer",
        quote: "The Ad Copy and Hashtag Generators are my go-to tools for every campaign. They save me so much time on research and consistently deliver great results.",
        avatar: "https://i.pravatar.cc/150?u=mike",
        rating: 5,
    }
];

const faqs = [
    {
        question: "Are all the AI tools on this website completely free?",
        answer: "Yes, absolutely! All tools available on AI Toolkit Pro are 100% free to use. We believe in making powerful AI technology accessible to everyone without any cost."
    },
    {
        question: "Do I need to create an account to use the tools?",
        answer: "No login or sign-up is required for most of our tools. You can start using them right away. We may introduce optional accounts for saving history or preferences in the future."
    },
    {
        question: "Is the content generated by these tools safe for commercial use?",
        answer: "Generally, yes. The content is generated by leading AI models. However, you are responsible for ensuring the final content does not infringe on any existing copyrights. We recommend reviewing our Copyright Disclaimer for more details."
    },
    {
        question: "Which AI models do you use for your tools?",
        answer: "We use a variety of state-of-the-art AI models from providers like Google (Gemini), OpenAI, and other specialized platforms to power our diverse range of tools, ensuring you get the best quality output for each task."
    },
    {
        question: "Is my data safe? Do you store my inputs?",
        answer: "We prioritize your privacy. We do not store the inputs you provide or the content you generate on our servers. Your data is processed by the respective AI API and the results are returned to you. Please see our Privacy Policy for more."
    },
    {
        question: "Is the website design AdSense friendly?",
        answer: "Yes, the website has been designed with clear navigation, user-friendly layout, and high-quality content structure to be fully compatible with Google AdSense policies, increasing the likelihood of approval."
    },
    {
        question: "Can I request a new AI tool to be added?",
        answer: "We'd love to hear your ideas! Please use our Contact Us page to send us your suggestions for new tools. We are always looking to expand our toolkit to better serve our users."
    }
];

const INITIAL_VISIBLE_TOOLS = 9;
const TOOLS_TO_LOAD = 9;

const NativeAdPlaceholder = () => (
    <div className="group flex animate-float-in">
        <Card className="w-full transition-all duration-300 flex flex-col bg-muted/50 backdrop-blur-sm border-dashed">
            <CardContent className="p-4 flex flex-col items-center justify-center text-center flex-grow">
                <div className="w-full h-full min-h-[150px] flex items-center justify-center">
                    <span className="text-muted-foreground text-sm">Demo Native Ad</span>
                </div>
            </CardContent>
        </Card>
    </div>
);

const BannerAdPlaceholder = ({ className }: { className?: string }) => (
    <div className={cn("container my-8", className)}>
        <div className="mx-auto w-full max-w-[728px] h-[90px] bg-muted/50 border border-dashed rounded-lg flex items-center justify-center">
            <span className="text-muted-foreground text-sm">Demo Banner Ad (728x90)</span>
        </div>
    </div>
);

export default function Home() {
  const plugin = useRef(
    Autoplay({ delay: 4000, stopOnInteraction: true })
  );
  const [visibleToolsCount, setVisibleToolsCount] = useState(INITIAL_VISIBLE_TOOLS);

  const handleLoadMore = () => {
    setVisibleToolsCount(prevCount => prevCount + TOOLS_TO_LOAD);
  };
  
  const itemsWithAds: JSX.Element[] = [];
  let toolCounter = 0;
  while(toolCounter < visibleToolsCount && toolCounter < allTools.length) {
    // Add 3 tools
    for(let i = 0; i < 3; i++) {
        if (toolCounter < allTools.length) {
            const tool = allTools[toolCounter];
            itemsWithAds.push(
                <Link href={tool.href} key={tool.name} className="group flex animate-float-in" style={{ animationDelay: `${0.1 + toolCounter * 0.05}s`}}>
                  <Card className="w-full transition-all duration-300 hover:shadow-2xl hover:-translate-y-2 hover:border-primary/50 flex flex-col bg-card/50 backdrop-blur-sm">
                    <CardContent className="p-4 flex flex-col items-center justify-center text-center flex-grow">
                      <div className="p-3 mb-3 rounded-lg bg-primary/10 text-primary transition-all duration-300 group-hover:scale-110 group-hover:bg-primary group-hover:text-primary-foreground">
                        {tool.icon}
                      </div>
                      <p className="font-semibold text-sm">{tool.name}</p>
                      <p className="text-xs text-muted-foreground mt-1">{tool.category}</p>
                    </CardContent>
                  </Card>
                </Link>
            );
            toolCounter++;
        }
    }

    // Add 3 ads
    if(toolCounter < allTools.length && toolCounter < visibleToolsCount) {
        for(let i = 0; i < 3; i++) {
            itemsWithAds.push(<NativeAdPlaceholder key={`ad-row-${Math.floor(toolCounter / 3)}-${i}`} />);
        }
    }
  }


  return (
    <div className="flex flex-col">
      <section className="py-16 md:py-24 text-center">
        <div className="container">
          <h1 className="font-headline text-4xl md:text-6xl font-bold gradient-text animate-float-in">
            AI Toolkit Pro
          </h1>
          <p className="mt-4 max-w-2xl mx-auto text-base md:text-lg text-muted-foreground animate-float-in" style={{ animationDelay: '0.1s' }}>
            Your ultimate suite of free AI tools. Generate ad copy, create scripts, design logos, find SEO keywords, and much more. Boost your productivity with our all-in-one toolkit.
          </p>
          <div className="mt-8 flex justify-center gap-4 animate-float-in" style={{ animationDelay: '0.2s' }}>
            <Button asChild size="lg">
              <Link href="/tools">
                Browse All Tools <ArrowRight className="ml-2 h-5 w-5" />
              </Link>
            </Button>
          </div>
        </div>
      </section>

      <BannerAdPlaceholder />

      {/* Tools Section */}
      <section id="tools" className="py-12">
        <div className="container px-4">
          <h2 className="font-headline text-3xl font-bold text-center mb-8">
            <span className="gradient-text">Popular AI Tools</span>
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {itemsWithAds}
          </div>
          {visibleToolsCount < allTools.length && (
            <div className="mt-8 text-center">
              <Button onClick={handleLoadMore} size="lg" variant="outline">
                Load More Tools
              </Button>
            </div>
          )}
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-16">
        <div className="container px-4">
          <h2 className="font-headline text-3xl font-bold text-center mb-8">What Our Users Say</h2>
          <Carousel
            plugins={[plugin.current]}
            opts={{
              align: "start",
              loop: true,
            }}
            className="w-full max-w-4xl mx-auto"
            onMouseEnter={plugin.current.stop}
            onMouseLeave={plugin.current.reset}
          >
            <CarouselContent className="-ml-4">
              {testimonials.map((testimonial, index) => (
                <CarouselItem key={index} className="pl-4 md:basis-1/2 lg:basis-1/3">
                    <Card className="h-full flex flex-col bg-card/50 backdrop-blur-sm shadow-lg">
                      <CardContent className="p-6 flex-grow flex flex-col justify-center">
                        <p className="text-muted-foreground italic text-sm mb-4 flex-grow">"{testimonial.quote}"</p>
                        <div className="flex items-center gap-3">
                            <Avatar className="w-10 h-10 border-2 border-primary/20">
                                <AvatarImage src={testimonial.avatar} alt={testimonial.name} />
                                <AvatarFallback>{testimonial.name.charAt(0)}</AvatarFallback>
                            </Avatar>
                            <div>
                                <h4 className="font-bold text-sm">{testimonial.name}</h4>
                                <p className="text-xs text-muted-foreground">{testimonial.title}</p>
                            </div>
                        </div>
                      </CardContent>
                    </Card>
                </CarouselItem>
              ))}
            </CarouselContent>
          </Carousel>
        </div>
      </section>

      <BannerAdPlaceholder />
      
      {/* FAQ Section */}
      <section className="py-16 md:py-24">
        <div className="container max-w-3xl">
          <h2 className="font-headline text-3xl font-bold text-center mb-8">
            Frequently Asked Questions
          </h2>
          <Accordion type="single" collapsible className="w-full space-y-4">
            {faqs.map((faq, index) => (
                <AccordionItem 
                    value={`item-${index}`} 
                    key={index}
                    className="bg-card/50 backdrop-blur-sm border border-border/50 rounded-xl px-6 animate-pop-in"
                    style={{ animationDelay: `${index * 0.1}s`}}
                >
                    <AccordionTrigger className="font-headline text-lg text-left hover:no-underline">{faq.question}</AccordionTrigger>
                    <AccordionContent className="text-base text-muted-foreground">
                        {faq.answer}
                    </AccordionContent>
                </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>
    </div>
  );
}
