'use client';

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { ArrowRight, BookOpen, Clock, Sparkles } from "lucide-react";
import Link from "next/link";
import { useRef, useState, useEffect } from "react";
import { allTools } from "@/lib/tools";
import { Carousel, CarouselContent, CarouselItem } from "@/components/ui/carousel";
import Autoplay from "embla-carousel-autoplay";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import Image from "next/image";
import { Badge } from "@/components/ui/badge";
import { BlogPost } from "@/lib/storage-types";

const testimonials = [
    {
        name: "Alex Rivera",
        title: "Content Creator",
        quote: "The AI Script Writer is a game-changer! I went from spending hours on a video script to drafting one in minutes. My productivity has skyrocketed.",
        avatar: "https://i.pravatar.cc/150?u=alex",
        rating: 5,
    },
    {
        name: "Samantha Lee",
        title: "Small Business Owner",
        quote: "I created a professional logo for my new business in under 60 seconds using the AI Logo Maker. It's free, fast, and the results are stunning. Highly recommend!",
        avatar: "https://i.pravatar.cc/150?u=samantha",
        rating: 5,
    },
    {
        name: "Mike Chen",
        title: "Digital Marketer",
        quote: "The Ad Copy and Hashtag Generators are my go-to tools for every campaign. They save me so much time on research and consistently deliver great results.",
        avatar: "https://i.pravatar.cc/150?u=mike",
        rating: 5,
    }
];

const faqs = [
    {
        question: "Are all the AI tools on this website completely free?",
        answer: "Yes, absolutely! All tools available on AI Toolkit Pro are 100% free to use. You can generate text, code, images, scripts, emails, and much more without paying anything or entering a credit card."
    },
    {
        question: "Do I need to create an account to use the tools?",
        answer: "No account is required to use any of our AI tools. You can use them immediately as a guest for free. Creating a free account allows you to securely save your generated content, prompt history, and favorite results in your profile."
    },
    {
        question: "What is the benefit of creating a free account?",
        answer: "When you create a free account, all your AI generations, favorite prompt templates, and output history are safely saved in your account. Without an account, you can still use all tools freely, but generated data is not saved across sessions."
    },
    {
        question: "Is the content generated by these tools safe for commercial use?",
        answer: "Generally, yes. The content is generated by leading AI models. However, you are responsible for ensuring the final content does not infringe on any existing copyrights. We recommend reviewing our Copyright Disclaimer for more details."
    },
    {
        question: "Which AI models do you use for your tools?",
        answer: "We use state-of-the-art AI models including Google Gemini to power our diverse suite of tools, ensuring you get fast, high-quality output for each task."
    },
    {
        question: "Is my personal data safe?",
        answer: "We prioritize your privacy. We do not sell your personal information, and your prompts are processed securely. Please review our Privacy Policy for more details."
    }
];

const INITIAL_VISIBLE_TOOLS = 12;
const TOOLS_TO_LOAD = 9;

export default function Home() {
  const plugin = useRef(
    Autoplay({ delay: 4000, stopOnInteraction: true })
  );
  const [visibleToolsCount, setVisibleToolsCount] = useState(INITIAL_VISIBLE_TOOLS);
  const [latestPosts, setLatestPosts] = useState<BlogPost[]>([]);

  useEffect(() => {
    async function loadFeaturedBlog() {
      try {
        const res = await fetch('/api/blog');
        const data = await res.json();
        if (data.success && data.posts) {
          setLatestPosts(data.posts.slice(0, 3));
        }
      } catch (e) {
        console.error(e);
      }
    }
    loadFeaturedBlog();
  }, []);

  const handleLoadMore = () => {
    setVisibleToolsCount(prevCount => prevCount + TOOLS_TO_LOAD);
  };
  
  const visibleTools = allTools.slice(0, visibleToolsCount);

  return (
    <div className="flex flex-col">
      <section className="pt-16 pb-8 md:pt-24 text-center">
        <div className="container">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary/10 border border-primary/20 text-xs font-semibold text-primary mb-6 animate-float-in">
            <Sparkles className="h-3.5 w-3.5" />
            <span>Over 20+ Free AI Generation Tools Available</span>
          </div>

          <h1 className="font-headline text-4xl md:text-6xl font-bold gradient-text animate-float-in">
            AI Toolkit Pro
          </h1>
          <p className="mt-4 max-w-2xl mx-auto text-base md:text-lg text-muted-foreground animate-float-in" style={{ animationDelay: '0.1s' }}>
            Your ultimate suite of free AI tools. Generate ad copy, create scripts, design logos, find SEO keywords, and boost creativity with high-ranking tutorials.
          </p>
          <div className="mt-8 flex flex-wrap justify-center gap-4 animate-float-in" style={{ animationDelay: '0.2s' }}>
            <Button asChild size="lg" className="font-semibold shadow-lg shadow-primary/20">
              <Link href="/tools">
                Browse All Tools <ArrowRight className="ml-2 h-5 w-5" />
              </Link>
            </Button>
            <Button asChild size="lg" variant="outline" className="font-semibold">
              <Link href="/blog">
                <BookOpen className="mr-2 h-4 w-4" />
                Read SEO Guides & Blog
              </Link>
            </Button>
          </div>
        </div>
      </section>

      {/* Tools Section */}
      <section id="tools" className="py-12">
        <div className="container px-4">
          <h2 className="font-headline text-3xl font-bold text-center mb-8">
            <span className="gradient-text">Popular AI Tools</span>
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            {visibleTools.map((tool, index) => (
               <Link href={tool.href} key={tool.name} className="group flex animate-float-in" style={{ animationDelay: `${0.1 + index * 0.05}s`}}>
                <Card className="w-full transition-all duration-300 hover:shadow-2xl hover:-translate-y-2 hover:border-primary/50 flex flex-col bg-card/50 backdrop-blur-sm">
                  <CardContent className="p-4 flex flex-col items-center justify-center text-center flex-grow">
                    <div className="p-3 mb-3 rounded-lg bg-primary/10 text-primary transition-all duration-300 group-hover:scale-110 group-hover:bg-primary group-hover:text-primary-foreground">
                      {tool.icon}
                    </div>
                    <p className="font-semibold text-sm">{tool.name}</p>
                    <p className="text-xs text-muted-foreground mt-1">{tool.category}</p>
                  </CardContent>
                </Card>
              </Link>
            ))}
          </div>
          {visibleToolsCount < allTools.length && (
            <div className="mt-8 text-center">
              <Button onClick={handleLoadMore} size="lg" variant="outline">
                Load More Tools
              </Button>
            </div>
          )}
        </div>
      </section>

      {/* Featured Blog & Tutorials Section for SEO & Traffic */}
      {latestPosts.length > 0 && (
        <section className="py-16 bg-muted/20 border-y border-border/40">
          <div className="container px-4">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-8">
              <div>
                <h2 className="font-headline text-2xl sm:text-3xl font-bold">
                  <span className="gradient-text">Latest AI Guides & Blog Posts</span>
                </h2>
                <p className="text-xs sm:text-sm text-muted-foreground mt-1">
                  Master prompts, rank on Google, and supercharge your workflow with our in-depth tutorials.
                </p>
              </div>
              <Link href="/blog">
                <Button variant="outline" size="sm" className="gap-1.5 text-xs font-semibold">
                  <span>View All Articles</span>
                  <ArrowRight className="h-3.5 w-3.5" />
                </Button>
              </Link>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {latestPosts.map((post) => (
                <Link
                  key={post.id}
                  href={`/blog/${post.slug}`}
                  className="group flex flex-col rounded-2xl border border-border bg-card overflow-hidden shadow-sm hover:shadow-xl transition-all duration-300 hover:-translate-y-1"
                >
                  <div className="relative h-48 w-full overflow-hidden bg-muted">
                    <Image
                      src={post.featuredImage}
                      alt={post.title}
                      fill
                      className="object-cover transition-transform duration-500 group-hover:scale-105"
                      referrerPolicy="no-referrer"
                    />
                    <div className="absolute top-3 left-3">
                      <Badge className="bg-background/90 text-foreground backdrop-blur-md text-[11px] font-semibold">
                        {post.category}
                      </Badge>
                    </div>
                  </div>
                  <div className="p-5 flex-1 flex flex-col justify-between space-y-3">
                    <div className="space-y-2">
                      <div className="flex items-center gap-2 text-[11px] text-muted-foreground">
                        <Clock className="h-3 w-3" />
                        <span>{post.readTime}</span>
                        <span>•</span>
                        <span>{new Date(post.datePublished).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</span>
                      </div>
                      <h3 className="font-bold text-base line-clamp-2 group-hover:text-primary transition-colors">
                        {post.title}
                      </h3>
                      <p className="text-xs text-muted-foreground line-clamp-2 leading-relaxed">
                        {post.description}
                      </p>
                    </div>
                    <div className="pt-2 flex items-center text-xs font-semibold text-primary gap-1 group-hover:translate-x-1 transition-transform">
                      <span>Read Guide</span>
                      <ArrowRight className="h-3.5 w-3.5" />
                    </div>
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* Testimonials Section */}
      <section className="py-16">
        <div className="container px-4">
          <h2 className="font-headline text-3xl font-bold text-center mb-8">What Our Users Say</h2>
          <Carousel
            plugins={[plugin.current]}
            opts={{
              align: "start",
              loop: true,
            }}
            className="w-full max-w-4xl mx-auto"
            onMouseEnter={plugin.current.stop}
            onMouseLeave={plugin.current.reset}
          >
            <CarouselContent className="-ml-4">
              {testimonials.map((testimonial, index) => (
                <CarouselItem key={index} className="pl-4 md:basis-1/2 lg:basis-1/3">
                    <Card className="h-full flex flex-col bg-card/50 backdrop-blur-sm shadow-lg">
                      <CardContent className="p-6 flex-grow flex flex-col justify-center">
                        <p className="text-muted-foreground italic text-sm mb-4 flex-grow">"{testimonial.quote}"</p>
                        <div className="flex items-center gap-3">
                            <Avatar className="w-10 h-10 border-2 border-primary/20">
                                <AvatarImage src={testimonial.avatar} alt={testimonial.name} />
                                <AvatarFallback>{testimonial.name.charAt(0)}</AvatarFallback>
                            </Avatar>
                            <div>
                                <h4 className="font-bold text-sm">{testimonial.name}</h4>
                                <p className="text-xs text-muted-foreground">{testimonial.title}</p>
                            </div>
                        </div>
                      </CardContent>
                    </Card>
                </CarouselItem>
              ))}
            </CarouselContent>
          </Carousel>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-16 md:py-24">
        <div className="container max-w-3xl">
          <h2 className="font-headline text-3xl font-bold text-center mb-8">
            Frequently Asked Questions
          </h2>
          <Accordion type="single" collapsible className="w-full space-y-4">
            {faqs.map((faq, index) => (
                <AccordionItem 
                    value={`item-${index}`} 
                    key={index}
                    className="bg-card/50 backdrop-blur-sm border border-border/50 rounded-xl px-6 animate-pop-in"
                    style={{ animationDelay: `${index * 0.1}s`}}
                >
                    <AccordionTrigger className="font-headline text-lg text-left hover:no-underline">{faq.question}</AccordionTrigger>
                    <AccordionContent className="text-base text-muted-foreground">
                        {faq.answer}
                    </AccordionContent>
                </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>
    </div>
  );
}
