import { config } from 'dotenv';
config();

import '@/ai/flows/ai-script-writer.ts';
import '@/ai/flows/voice-to-text-converter.ts';
import '@/ai/flows/text-to-speech-converter.ts';
import '@/ai/flows/ai-image-generator.ts';
import '@/ai/flows/text-translator.ts';
import '@/ai/flows/ai-question-answering.ts';
import '@/ai/flows/coding-help-assistant.ts';
import '@/ai/flows/grammar-spelling-corrector.ts';
import '@/ai/flows/text-rewriter.ts';
import '@/ai/flows/social-media-post-generator.ts';
import '@/ai/flows/quiz-generator.ts';
import '@/ai/flows/meme-generator.ts';
import '@/ai/flows/background-remover.ts';
import '@/ai/flows/idea-generator.ts';
import '@/ai/flows/ai-logo-generator.ts';
import '@/ai/flows/product-description-generator.ts';
import '@/ai/flows/story-plot-generator.ts';
import '@/ai/flows/hashtag-generator.ts';
import '@/ai/flows/slogan-generator.ts';
import '@/ai/flows/ad-copy-generator.ts';
