import { type Metadata } from 'next';
import { AiRecipeMakerClient } from '@/components/ai-recipe-maker-client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { CheckCircle } from 'lucide-react';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"


export const metadata: Metadata = {
  title: 'Free AI Recipe Maker | Recipes from Your Ingredients',
  description: 'Generate delicious recipes based on the ingredients you have at home. Our free AI tool helps you cook amazing meals and reduce food waste.',
};

const benefits = [
    "Reduce food waste by using what you have.",
    "Discover new and exciting meal ideas.",
    "Get recipes for any cuisine or dietary need.",
    "Save time on meal planning and grocery lists."
];

const faqs = [
    {
        question: "1. Is this tool free?",
        answer: "Yes, our AI Recipe Maker is 100% free to use. There are no hidden fees or subscriptions."
    },
    {
        question: "2. Do I need to have all the ingredients?",
        answer: "The AI will prioritize the ingredients you list but may include common pantry staples like salt, pepper, or oil. It's designed to be flexible."
    },
    {
        question: "3. Can I use this for any dietary restriction?",
        answer: "Absolutely. You can specify preferences like 'vegetarian,' 'gluten-free,' 'vegan,' or 'low-carb' to get recipes that fit your needs."
    },
    {
        question: "4. How many recipes does it generate?",
        answer: "The tool generates 3 unique and complete recipe ideas at a time, each with a title, description, ingredient list, and step-by-step instructions."
    },
    {
        question: "5. Can I get recipes from a specific cuisine?",
        answer: "Yes! You can choose from a wide range of cuisines like Italian, Mexican, Indian, and more to tailor the recipes to your taste."
    },
    {
        question: "6. What if I only have a few ingredients?",
        answer: "Even with just a few ingredients, the AI will do its best to generate creative recipes. For best results, try to list at least 3-4 main ingredients."
    },
    {
        question: "7. Are the cooking times accurate?",
        answer: "The cooking times are estimates generated by the AI. They are generally accurate but can vary depending on your specific appliances and cooking pace."
    }
];

export default function AiRecipeMakerPage() {
  return (
    <div className="container py-12 md:py-20">
      <div className="grid lg:grid-cols-5 gap-12">
        <div className="lg:col-span-3">
            <h1 className="font-headline text-4xl md:text-5xl font-bold gradient-text">
                AI Recipe Maker
            </h1>
            <p className="mt-4 text-lg text-muted-foreground">
                Don't know what to cook? Enter the ingredients you have, and let our AI create delicious recipes for you. Our free AI recipe maker helps you discover new meal ideas, reduce food waste, and save time on meal planning. Whether you have specific dietary needs or want to explore a new cuisine, this tool provides step-by-step instructions for breakfast, lunch, and dinner. Cook amazing meals with the ingredients already in your kitchen.
            </p>

            <div className="mt-8">
                <AiRecipeMakerClient />
            </div>
        </div>
        <div className="lg:col-span-2 space-y-8">
            <Card className="bg-card/50">
                <CardHeader>
                    <CardTitle className="font-headline text-2xl">How to Use</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                    <p><strong>1. List Ingredients:</strong> Enter the ingredients you have on hand, separated by commas.</p>
                    <p><strong>2. Set Preferences:</strong> Choose your desired cuisine, meal type, and any dietary restrictions.</p>
                    <p><strong>3. Generate:</strong> Click the "Generate Recipes" button to get unique recipe ideas.</p>
                    <p><strong>4. Cook & Enjoy:</strong> Follow the step-by-step instructions and enjoy your meal!</p>
                </CardContent>
            </Card>

             <Card className="bg-card/50">
                <CardHeader>
                    <CardTitle className="font-headline text-2xl">Benefits</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                    {benefits.map((benefit, index) => (
                        <div key={index} className="flex items-start">
                            <CheckCircle className="h-5 w-5 text-green-500 mr-3 mt-1 flex-shrink-0" />
                            <span>{benefit}</span>
                        </div>
                    ))}
                </CardContent>
            </Card>

            <Card className="bg-card/50">
                <CardHeader>
                    <CardTitle className="font-headline text-2xl">Frequently Asked Questions</CardTitle>
                </CardHeader>
                <CardContent>
                    <Accordion type="single" collapsible className="w-full space-y-4">
                        {faqs.map((faq, index) => (
                             <AccordionItem 
                                value={`item-${index + 1}`} 
                                key={index} 
                                className="bg-background/50 border rounded-lg transition-all duration-300 data-[state=open]:border-primary data-[state=open]:shadow-lg data-[state=open]:shadow-primary/10"
                            >
                                <AccordionTrigger className="text-left px-6 hover:no-underline font-semibold">
                                    {faq.question}
                                </AccordionTrigger>
                                <AccordionContent className="px-6 pb-6">
                                    {faq.answer}
                                </AccordionContent>
                            </AccordionItem>
                        ))}
                    </Accordion>
                </CardContent>
            </Card>
        </div>
      </div>
    </div>
  );
}
