
import { type Metadata } from 'next';
import { Card, CardContent } from '@/components/ui/card';

export const metadata: Metadata = {
  title: 'Terms and Conditions | AI Toolkit Pro',
  description: 'Please read our Terms and Conditions carefully before using the tools provided by AI Toolkit Pro. Your use of the service constitutes acceptance of these terms.',
  keywords: ['terms and conditions', 'terms of service', 'website terms', 'ai tools terms'],
   openGraph: {
    title: 'Terms and Conditions | AI Toolkit Pro',
    description: 'Read the terms and conditions for using our free AI tools.',
    url: 'https://www.aitoolkitpro.com/terms-and-conditions',
    type: 'website',
  },
  twitter: {
    card: 'summary',
    title: 'Terms and Conditions | AI Toolkit Pro',
    description: 'Our terms of service.',
  },
};

const schema = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  "name": "Terms and Conditions",
  "url": "https://www.aitoolkitpro.com/terms-and-conditions",
  "description": "Please read our Terms and Conditions carefully before using the tools provided by AI Toolkit Pro.",
  "publisher": {
    "@type": "Organization",
    "name": "AI Toolkit Pro",
    "logo": {
      "@type": "ImageObject",
      "url": "https://www.aitoolkitpro.com/logo.png"
    }
  }
};

export default function TermsAndConditionsPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <div className="container max-w-3xl p-4 sm:p-6 md:p-8">
        <div className="text-center mb-10">
            <h1 className="font-headline text-3xl md:text-4xl font-bold">Terms and Conditions</h1>
            <p className="mt-2 text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
        </div>

        <Card className="bg-card/50">
            <CardContent className="p-6 space-y-6 text-sm md:text-base text-muted-foreground">
                <p>
                  By accessing and using AI Toolkit Pro, you agree to be bound by these Terms and Conditions. If you disagree with any part of the terms, you may not use our services.
                </p>

                <div className="space-y-2">
                  <h2 className="text-lg font-semibold text-foreground">1. Use of Tools</h2>
                  <p>
                    All tools provided on AI Toolkit Pro are free to use. You agree not to use the tools for any illegal or unauthorized purpose. You are solely responsible for the content you generate and its use.
                  </p>
                </div>
                
                <div className="space-y-2">
                  <h2 className="text-lg font-semibold text-foreground">2. Intellectual Property</h2>
                  <p>
                    The content generated by the AI is provided by third-party services. You are responsible for ensuring that your use of the generated content complies with all applicable laws and the terms of the respective API providers. We do not claim any ownership rights over the content you generate.
                  </p>
                </div>

                <div className="space-y-2">
                  <h2 className="text-lg font-semibold text-foreground">3. Disclaimer of Warranties</h2>
                  <p>
                    The services are provided on an "as is" and "as available" basis. AI Toolkit Pro makes no warranties, expressed or implied, and hereby disclaims all other warranties including, without limitation, implied warranties of merchantability, fitness for a particular purpose, or non-infringement of intellectual property.
                  </p>
                </div>

                <div className="space-y-2">
                  <h2 className="text-lg font-semibold text-foreground">4. Limitation of Liability</h2>
                  <p>
                    In no event shall AI Toolkit Pro or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on our website.
                  </p>
                </div>

                <div className="space-y-2">
                  <h2 className="text-lg font-semibold text-foreground">5. Governing Law</h2>
                  <p>
                    These terms and conditions are governed by and construed in accordance with the laws of our jurisdiction and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.
                  </p>
                </div>

                <div className="space-y-2">
                  <h2 className="text-lg font-semibold text-foreground">6. Contact Us</h2>
                  <p>
                    If you have any questions about these Terms, please contact us.
                  </p>
                </div>
            </CardContent>
        </Card>
      </div>
    </>
  );
}
