import { type Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms and Conditions',
  description: 'Please read our Terms and Conditions carefully before using the tools provided by AI Toolkit Pro.',
};

export default function TermsAndConditionsPage() {
  return (
    <div className="container py-12 md:py-20">
      <div className="max-w-4xl mx-auto prose dark:prose-invert">
        <h1 className="font-headline text-4xl md:text-5xl font-bold">Terms and Conditions</h1>
        <p className="lead">Last updated: {new Date().toLocaleDateString()}</p>
        
        <p>
          By accessing and using AI Toolkit Pro, you agree to be bound by these Terms and Conditions. If you disagree with any part of the terms, you may not use our services.
        </p>

        <h2>1. Use of Tools</h2>
        <p>
          All tools provided on AI Toolkit Pro are free to use. You agree not to use the tools for any illegal or unauthorized purpose. You are solely responsible for the content you generate and its use.
        </p>
        
        <h2>2. Intellectual Property</h2>
        <p>
          The content generated by the AI is provided by third-party services. You are responsible for ensuring that your use of the generated content complies with all applicable laws and the terms of the respective API providers. We do not claim any ownership rights over the content you generate.
        </p>

        <h2>3. Disclaimer of Warranties</h2>
        <p>
          The services are provided on an "as is" and "as available" basis. AI Toolkit Pro makes no warranties, expressed or implied, and hereby disclaims all other warranties including, without limitation, implied warranties of merchantability, fitness for a particular purpose, or non-infringement of intellectual property.
        </p>

        <h2>4. Limitation of Liability</h2>
        <p>
          In no event shall AI Toolkit Pro or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on our website.
        </p>

        <h2>5. Governing Law</h2>
        <p>
          These terms and conditions are governed by and construed in accordance with the laws of our jurisdiction and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.
        </p>

        <h2>6. Contact Us</h2>
        <p>
          If you have any questions about these Terms, please contact us.
        </p>
      </div>
    </div>
  );
}
